kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
  namespace: planespotter
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi